### ISSUE TITLE
Moving lwc.config to project.json > "lwc" doesn't work

### ISSUE THREAD

**Issue by itsmebasti** [trailheadapps/lwc-recipes-oss#161]
### Summary

I am currently getting warm with developing lwc outside of SF so I am playing around with different things. But currently I encounter some things that are not working as documented: Moving the lwc config into the package.json does not work for me.
Please let me know if this issue is better raised at the lwc or lwc/module-resolver repo.

### Steps To Reproduce:

1.  add lwc the key to package.json (should work as documented here: [@lwc/module-resolver](https://github.com/salesforce/lwc/tree/master/packages/%40lwc/module-resolver))
1. copy the content form lwc.config.json
```
    ...},
    "lwc" : {
        "modules": [
            {
                "dir": "src/modules"
            },
            {
                "npm": "lwc-recipes-oss-ui-components"
            }
        ]
    },

    "engines": {...
```
3. remove the existing lwc.config.json

### Expected result

The app should work the same way as before.

### Actual result

```
�  Starting build process.
�  Local server listening: http://localhost:3001
× ｢wdm｣:
ERROR in ./src/modules/ui/app/app.js 4:24
Module parse failed: Unexpected token (4:24)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import { navigationItems, navigationElements } from './navigation';
| export default class App extends LightningElement {
>   currentNavigationItem = 'hello';
|   navigationItems = navigationItems;
|   nextNavigationItem;
 @ ./src/index.js 3:0-27 6:6-11
 @ multi ./node_modules/error-overlay-webpack-plugin/lib/entry-basic.js ./node_modules/error-overlay-webpack-plugin/lib/entry-devserver.js? ./src/index.js
```

### Additional information

Am I missing something here (I am pretty new to this field) or is it not working as expected?

**Comment by itsmebasti** [comment]
I experience the same for my babel.config and the "babel" key, that I use to load classes from outside /modules that are using properties ("@babel/plugin-proposal-class-properties")

**Comment by adityanaag3** [comment]
Hey @itsmebasti : I just tried this on my own project, and module resolution works fine in both the cases - `lwc` key in package.json, and lwc.config.json file. 

The error message seems to hint more towards an error in parsing than error in resolving the module. Can you try deleting the `node_modules` folder and re-running the command `npm install`?

**Comment by itsmebasti** [comment]
Missing details: 
I am only testing it locally, using `yarn watch`, this is where it fails, how are you executing it?
I was using yarn install instead of npm, but both result in the same error
I also removed the yarn.lock just to be sure, nothing helped.

I did exactly what you described and it still fails.

since I didn't upgrade I am running on
"lwc-services": "^2.3.0"
npm version is 6.14.9
yarn version is 1.22.5

**Comment by adityanaag3** [comment]
There was an issue with the latest version of lwc-services, which we just fixed. Please pull the latest yarn.lock file from the master branch, and re-run yarn or npm install.

**Comment by itsmebasti** [comment]
great, it works! thank you!

besides this issue, do you have any hint on how I could solve the same issue for babel?

    "babel" : {
        "plugins": [
            "@babel/plugin-proposal-class-properties"
        ]
    }

is currently just ignored and only considered when I am using a babel config file instead.

**Comment by adityanaag3** [comment]
I am not sure how to resolve the babel issue - I've never used that previously.
