### ISSUE TITLE
Add recipe for Lightning Out

### ISSUE THREAD

**Issue by neidenmark** [trailheadapps/lwc-recipes-oss#17]
**What is missing from the application? Please describe.**
How to use Lightning Out components in lwc.dev apps. D3, Moment etc already exists.

**Comment by muenzpraeger** [comment]
I don't see a use case for such a recipe, or implementation, in general for multiple reasons.

First, there is no real use case to use a Lightning web component OSS at all. As Lightning Out needs to modify the DOM only a blank component with a tag using `lwc:dom=manual` is all that would be needed. This is covered already by the existing recipes that are mentioned above.

Second, and that's the main concern is that using Lightning Out will inject the LWC engine into the page. At the same time the LWC OSS version of the engine will already be on that page. As those versions are not in sync this may have side-effects on the application.
