### ISSUE TITLE
apply css to rest api response html content in LWC

### ISSUE THREAD

**Issue by madhusitams004** [trailheadapps/lwc-recipes-oss#170]
**What is missing from the application? Please describe.**
I am calling one rest call in LWC js and getting response as HTML content. while displaying that html content in component I'd like to apply css.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adityanaag3** [comment]
Hey @madhusitams004 - You can place your styles in the component's CSS file. The CSS styles will apply to the HTML present in the HTML template as well as new elements appended to the DOM later on (including ones from the fetch() call)

**Comment by madhusitams004** [comment]
Thank you @adityanaag3 
Fixed this issue by creating css in static resouce and with meta xml config
<?xml version="1.0" encoding="UTF-8"?>
<StaticResource xmlns="http://soap.sforce.com/2006/04/metadata">
    <cacheControl>Public</cacheControl>
    <contentType>text/css</contentType>
</StaticResource>
