### ISSUE TITLE
What is <ui-card> or <ui-button> ?

### ISSUE THREAD

**Issue by deekshants** [trailheadapps/lwc-recipes-oss#53]
Hello, the project uses <ui-card> tag in  almost all the components, but the ui folder has no component named card or button. It only has app and navigation component, then what is this card or button component?
Because when I use these components, it shows the error saying that card is undefined

**Comment by pozil** [comment]
Hi @deekshants, these two components are base components just like `app` and `navbar` that we use to display recipes. They are not recipes on their own so their source code is stored in a dependency.

**Comment by deekshants** [comment]
thank you @pozil that helped, and I also found these base components in rw/webpack-imports branch

**Comment by charltonAthletic** [comment]
Hi - can you advise a bit more on what the actual solution is here? I am wasting so much time trying to understand where to get ui-card and other components from that are referenced in the Github repo for LWC OSS but are not in the actual repo itself. 

Please can you advise? 

https://salesforce.stackexchange.com/questions/295560/lwc-oss-cannot-find-ui-card-component

**Comment by kushagrabansal** [comment]
I simply created a LWC app , then tried to run the source code for lwc recipes in my app ,
it threw an error on using <ui-card> ,
so then i installed lwc-recipes-oss-ui-components , still the error persists :-

NoLwcModuleFound [Error]: Unable to resolve "ui/card" from "D:\SALESFORCE\May 10th\my-app"
    at Object.resolveModule (D:\SALESFORCE\May 10th\my-app\node_modules\@lwc\module-resolver\dist\commonjs\index.js:130:11)
    at Array.<anonymous> (D:\SALESFORCE\May 10th\my-app\node_modules\lwc-services\lib\utils\webpack\module-resolver.js:59:41)
    at Storage.finished (D:\SALESFORCE\May 10th\my-app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\SALESFORCE\May 10th\my-app\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at callback (D:\SALESFORCE\May 10th\my-app\node_modules\graceful-fs\polyfills.js:295:20)
    at FSReqCallback.oncomplete (fs.js:158:21) {
  code: 'NO_LWC_MODULE_FOUND'
}

**Comment by muenzpraeger** [comment]
@kushagrabansal Please ensure that you are using `lwc-services` 2.0.7.

**Comment by kushagrabansal** [comment]
@muenzpraeger  I am using lwc-services 2.0.7 , but the error persists ,                                               [this is the repo link](https://github.com/kushagrabansal/my-app) , please take a look at why this is happening .

**Comment by muenzpraeger** [comment]
@kushagrabansal You have to specify the modules that you want to get resolved by the LWC module resolver, see example [here](https://github.com/trailheadapps/lwc-recipes-oss/blob/master/package.json#L45-L51), based on the [module resolution RFC](https://rfcs.lwc.dev/rfcs/lwc/0020-module-resolution).

**Comment by kushagrabansal** [comment]
@muenzpraeger  I specified the module but got this error : my-app\node_modules\@lwc\module-resolver\dist\commonjs\utils.js:126
        throw new errors_1.LwcConfigError('Missing "expose" attribute: An imported npm package must explicitly define all the modules that it contains', { scope: opts.rootDir });

**Comment by muenzpraeger** [comment]
The npm package that you consume has to expose any components that it want to be consumed. You can find that information in the above linked RFC. Based on your repo link you should update `lwc-recipes-oss-ui-components` to 0.3.2.
