### ISSUE TITLE
Issue with {style} in chartBar component

### ISSUE THREAD

**Issue by shitalsonkuale** [trailheadapps/lwc-recipes-oss#65]
I am following chartBar component from LWC Recipes Repo. But when I add {style}, I am getting below errors: 
1.  } expectedcss(css-rcurlyexpected
2. at-rule or selector expectedcss(css-ruleorselectorexpected)

/****ChartBar.html***/
<div class="bar" style={style}></div>

/**ChartBar.js***/
  get style() {
        return `width: ${this.percentage}%`;
    }
Bar doesn't render on page for this component , only Percentage is displayed.

I have cloned the LWC Recipes Repo , and when i open chartBat.html in VS code , it's throwing same error.  Attached is the screenshot for the error. 
![ChartBar_style_error](https://user-images.githubusercontent.com/20252633/71161608-a7ca7900-226f-11ea-87c1-1c5a00d2c8a1.png)

**Comment by muenzpraeger** [comment]
This is not a real error. The built-in VS Code CSS linter doesn't know about the curly-braces notation within HTML files. It is related to [this issue](https://github.com/forcedotcom/salesforcedx-vscode/issues/1802).

**Comment by shitalsonkuale** [comment]
Thank you for clarifying muenzpraeger . 
I created a new project and deployed apiProperty and chartBar components to my trailhead playground, the bar rendered this time. 

However not sure why it didn't work in my scratch org even though I copy-pasted the components from Github. I will investigate more on that.
