### ISSUE TITLE
What is <ui-card> or <ui-button>

### ISSUE THREAD

**Issue by charltonAthletic** [trailheadapps/lwc-recipes-oss#75]
I have the same issue as was outlined here: https://github.com/trailheadapps/lwc-recipes-oss/issues/53

I simply want to preview the recipes in the LWC OSS repo on the LWC server. I cannot do that because the LWC server keeps throwing errors at run time that it cannot find ui-card amongst many others. 

What is the actual solution here?

**Comment by muenzpraeger** [comment]
These components are part of an external [npm package](https://github.com/trailheadapps/lwc-recipes-oss/blob/master/package.json#L9), as @pozil outlined in the other issue. The source is not yet open sourced, as the mechanism for component module resolution is in flux.

**Comment by charltonAthletic** [comment]
Thank you team :)

**Comment by charltonAthletic** [comment]
resolved
