### ISSUE TITLE
npm build is broken

### ISSUE THREAD

**Issue by albarivas** [trailheadapps/lwc-recipes-oss#85]
While the rest of the sample apps do support npm, this one only supports yarn. It can be confusing (it was for me). Can we adapt it to support it? @muenzpraeger

**Comment by muenzpraeger** [comment]
It is supported, but not used. The usage of `yarn` is aligned with LWC tooling, while the platform sample apps are aligned with what product ships.

**Comment by pozil** [comment]
@muenzpraeger it looks like the build doesn't work on npm anymore.
It use to work but something has changed perhaps it's a tooling issue more that a project issue.

I'm getting module resolution errors like this when running tests with npm:
> Cannot find module 'ui/button' from 'paginator.html'

Here's what I did to reproduce:
- deleted my `node_modules` folder (I had that from a previous yarn install)
- forced cache refresh with `npm cache clean --force`
- installed project with `npm install`
- ran the tests `npm run unit:test`
- go a bunch of module resolution errors for the `ui/` components.

**Comment by muenzpraeger** [comment]
What you mention @pozil is related to [this](https://github.com/trailheadapps/lwc-recipes-oss/pull/81#issuecomment-607154454), not the chosen package manager that @albarivas mentioned here.

**Comment by pozil** [comment]
Indeed but what's weird is that I don't have the issue with yarn. Something is weird with the cache...

I don't experience the same issue with that flow:

```sh
rm -fr node_modules
yarn cache clean
yarn install
yarn run test:unit
```

**Comment by muenzpraeger** [comment]
That’s because there’s no `package-lock.json`.

**Comment by abhimanyud3dx** [comment]
adding "lwc-webpack-plugin": "^1.2.2", to package JSON fixed the issue for me.

**Comment by adityanaag3** [comment]
@abhimanyud3dx `lwc-services` internally already has `lwc-webpack-plugin` as a dependency. Just make sure your project uses the latest version of `lwc-services` and you should be good. I tried with both yarn and npm, and it works.
